package domain

import (
	"time"

	"github.com/google/uuid"
)

// Transfer represents a wallet-to-wallet money movement request.
type Transfer struct {
	ID             uuid.UUID
	IdempotencyKey string
	FromWalletID   uuid.UUID
	ToWalletID     uuid.UUID
	Amount         Amount
	Status         TransferStatus
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// NewTransfer constructs a new Transfer in PENDING state.
// The ID is generated by the domain layer using UUID v7 so that callers have the
// identifier before any persistence takes place.
func NewTransfer(fromWalletID, toWalletID uuid.UUID, idempotencyKey string, amount Amount) Transfer {
	now := time.Now().UTC()

	return Transfer{
		ID:             NewID(),
		IdempotencyKey: idempotencyKey,
		FromWalletID:   fromWalletID,
		ToWalletID:     toWalletID,
		Amount:         amount,
		Status:         TransferStatusPending,
		CreatedAt:      now,
		UpdatedAt:      now,
	}
}

// CanTransition reports whether moving a transfer from src to dst is a valid
// state-machine transition.
//
// Allowed transitions:
//
//	PENDING → PROCESSED
//	PENDING → FAILED
func CanTransition(src, dst TransferStatus) bool {
	switch src {
	case TransferStatusPending:
		return dst == TransferStatusProcessed || dst == TransferStatusFailed
	default:
		return false
	}
}
